### ISSUE TITLE
Clarify README.md

### ISSUE THREAD

**Issue by 7studio** [HugoGiraudel/ImagePreloader#2]
Hi Hugo,

I would like to propose two changes concerning some words in your README.md to avoid confusions:
1. Remove the "fully loaded" sentence in favour of "properly queued" because images aren't loaded in the `queue` method.
2. Prefer "preloaded" instead of "loaded" to be similar to your first example.

Your second example would look like that:

``` js
var deck1 = ['/image-1.png', 'image-2.jpg', 'http://lorempixel.com/200/400'];
var deck2 = ['image_4.jpg', '/34086368342.jpg', 'spacer.gif'];

// Instanciate new ImagePreloader
var ip = new ImagePreloader({
  // If `false`, then decks are loaded sequencially
  // If `true`, then decks are loaded in parallel
  parallel: true
});

// Queue the images
ip.queue(deck1).then(function () {
  console.log('First deck properly queued.');
});

ip.queue(deck2).then(function () {
  console.log('Second deck properly queued.');
});

// Preload the queue
ip.preload().then(function () {
  console.log('All decks fully preloaded.');
});
```

We could also point out the use of "fully loaded" for the `queue` method in the first paragraph.

> The idea is simple: you add decks (collections of images) to the preloader queue with the .queue(array) method. This method returns a Promise so you can use .then(..) on it to execute some code once it gets fully loaded.

I hope you will consider these changes.

**Comment by KittyGiraudel** [comment]
Sounds legit. Care to open a PR?

**Comment by KittyGiraudel** [comment]
Well, no. The code passed to the `.then(..)` on `.queue(..)` is executed once the deck is _fully loaded_, not _properly queued_. So the wording is actually correct here.

Agree, on _preloaded_ though.

**Comment by 7studio** [comment]
Sorry for the wrong understanding of your code Hugo :disappointed_relieved:
